name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.0' # The R version to download (if necessary) and use.
      
      - name: Install tidyverse linux dependencies
        run : sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages and transform json data to csv file using R
        run: sudo Rscript tests/transform_data.R
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: transformed_csv
          path: tests/search.csv
